data_path: /home/hjy22/repos/CIFAR10
val_data_path: /home/hjy22/repos/CIFAR10
dataset: cifar10
save_best: true
image_size: 256
vq_model: VQ-16
enc_type: simple
dec_type: simple
semantic_guide: none
detail_guide: none
global_batch_size: 32
epochs: 1
lr_scheduler: cosine
lr: 3e-5
#max_grad_norm: 1.0
#reconstruction_weight: 4.0
codebook_embed_dim: 32
codebook_size: 8192
abs_pos_embed: true
product_quant: 1
ema: true
codebook_drop: 0.0
encoder_model: vit_base_patch14_dinov2.lvd142m
decoder_model: vit_base_patch14_dinov2.lvd142m
num_latent_tokens: 256
v_patch_nums: [16]
half_sem: false
guide_type_1: class
start_drop: 3
log_every: 10000
vis_every: 10000
ckpt_every: 10000
sem_loss_weight: 0.1
enc_tuning_method: full
lecam_loss_weight: 0.001
weight_decay: 0.0
disc_weight_decay: 0.0005
#disc_epoch_start: 56
disc_epoch_start: 0
disc_type: dinodisc
aug_fade_steps: 0
disc_adaptive_weight: true
cloud_save_path: XQGAN-8192-simple-cifar10